[project]
name = "physics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pre-commit>=4.3.0",
    "ruff>=0.12.12",
    "scipy>=1.16.1",
    "streamlit>=1.49.1",
    "watchdog>=6.0.0",
]
