name: docker-build-push

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: physics-labs

    steps:
      - uses: actions/checkout@v5

      - name: Lowercase repo owner and set IMAGE_PATH
        run: |
          OWNER_LOWERCASE=${GITHUB_REPOSITORY_OWNER,,}
          echo "IMAGE_PATH=ghcr.io/${OWNER_LOWERCASE}/${IMAGE_NAME}" >> $GITHUB_ENV

      - name: set up QEMU (for multi-arch)
        uses: docker/setup-qemu-action@v3

      - name: set up buildx
        uses: docker/setup-buildx-action@v3

      - name: log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE_PATH }}:latest,${{ env.IMAGE_PATH }}:${{ github.sha }}
          platforms: linux/amd64,linux/arm64
